### ISSUE TITLE
[Question] Where to see how is the proper way using lang_code in URLs ? 

### ISSUE THREAD

**Issue by ufo911** [damyanbogoev/flask-bookshelf#4]
I have some example

https://stackoverflow.com/questions/49496761/two-language-flask-site-with-or-without-blueprints/49948870#49948870

but I am not sure if I correctly using some details, I need to have app without babel and international urls with lang_codes and logic for switching language and saving lang_code in cookie with blueprint or without it

**Comment by damyanbogoev** [comment]
You could use the solution implemented in this [pull request](https://github.com/damyanbogoev/flask-bookshelf/pull/5), powered by Sébastien Béal and the general approach described in the [blog post](https://damyanon.net/post/flask-series-internationalization/).
